# Generated by Django 2.1.3 on 2019-01-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
